repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
